name: Notify Slack on Pull Request

on:
  pull_request:
    types: [opened] # PRì´ ìƒˆë¡œ ìƒì„±ë  ë•Œë§Œ íŠ¸ë¦¬ê±°ë¨

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"ğŸ“¢ ${{ github.event.pull_request.title }} ê´€ë ¨ PRì´ ì—´ë ¸ì–´ìš”.\nğŸ™‹ ì‘ì„±ì: ${{ github.event.pull_request.user.login }}\nğŸ™‡â€â™‚ï¸ <@U07UR63D65R>ë‹˜ í™•ì¸ë¶€íƒë“œë¦½ë‹ˆë‹¤!\nğŸŒ <${{ github.event.pull_request.html_url }}|PR ë§í¬>", "username": "GitHub Bot"}' \
          $SLACK_WEBHOOK_URL
